import pathlib
import setuptools
import sys

install_requires = ["jira", "gql", "pyyaml"]
tests_require = ["pytest", "pytest-cov", "pytest-flake8", "pytest-black"]
dev_requires = install_requires + tests_require + ["documenteer[pipelines]"]
scm_version_template = """# Generated by setuptools_scm
__all__ = ["__version__"]
__version__ = "{version}"
"""

tools_path = pathlib.PurePosixPath(setuptools.__path__[0])
base_prefix = pathlib.PurePosixPath(sys.base_prefix)
data_files_path = tools_path.relative_to(base_prefix).parents[1]

setuptools.setup(
    name="vanward",
    description="Scripts to assist prior to certain steps in deploying a new cycle.",
    use_scm_version={
        "write_to": "python/lsst/ts/vanward/version.py",
        "write_to_template": scm_version_template,
    },
    setup_requires=["setuptools_scm"],
    install_requires=install_requires,
    package_dir={"": "python"},
    packages=setuptools.find_namespace_packages(where="python"),
    package_data={"": ["*.rst", "*.yaml"]},
    scripts=[
        "bin/check_software_release.py",
        "bin/merge_tickets.py",
        "bin/release_announcement.py",
        "bin/release_tickets.py",
    ],
    tests_require=tests_require,
    extras_require={"dev": dev_requires},
    license="GPL3",
    project_urls={
        "Bug Tracker": "https://jira.lsstcorp.org/secure/Dashboard.jspa",
        "Source Code": "https://github.com/lsst-ts/vanward",
    },
)
